version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096      # http web-frontend
      - 8920:8920      # https
      - 1900:1900/udp  # service discovery and dlna auto-discovery, can not be changed
      - 7359:7359/udp  # client auto-discorery, can not be changed
    volumes:
      - /path/to/config:/config
      - /path/to/cache:/cache
      - /path/to/media:/media
      - /path/to/media2:/media2:ro
    restart: "unless-stopped"
